package jemma.org.osgi.service.zigbee;

import java.math.BigInteger;

/**
 * This interface represents events generated by a ZigBee Device node
 * @author Jinyong Fu <fu@ismb.it>
 *
 */
public interface ZigBeeEvent {
	/**
	 * 
	 * @return The ZigBee device node IEEE Address.
	 */
	BigInteger getIEEEAddress();
	/**
	 * 
	 * @return The endpoint identifier.
	 */
	short getEndpointId();
	/**
	 * 
	 * @return The cluster id.
	 */
	int getClusterId();
	/**
	 * 
	 * @return the attribute identifier (i.e. the attribute's ID)
	 */
	int getAttributeId();
	/**
	 * 
	 * @return An object containing the new value for the ZigBee attribute that has changed.
	 */
	Object getValue();
}
