package jemma.org.osgi.service.zigbee;

/**
 * The ZigBeeDataOutput interface is designed for converting java data types into a series of bytes. 
 * The purpose of this interface is the same as the DataOutput interface provided by java, with the difference that in this interface, 
 * the generated bytes ordering is little endian, whereas in the DataOutput is big endian.
 * @author Jinyong Fu <fu@ismb.it>
 *
 */
public interface ZigBeeDataOutput {
	/**
	 * Appends a byte to the data output
	 * @param value
	 */
	void writeByte(byte value);
	/**
	 * Appends an int value to the data output.
	 * @param value
	 * @param size
	 */
	void writeInt(int value, int size);
	/**
	 * Appends a long to to the data output.
	 * @param value
	 * @param size
	 */
	void writeLong(long value, int size);
	/**
	 * Appends on the Data Output Stream a float value
	 * @param value
	 * @param size
	 */
	void writeFloat(float value, int size);
	/**
	 * Appends on the Data Output Stream a double value
	 * @param value
	 */
	void writeDouble(double value);
	/**
	 * Appends on the Data Output Stream a bytes value
	 * @param bytes
	 * @param length
	 */
	void writeBytes(byte[] bytes, int length);
}
